@baseUrl = http://localhost:8080
@contentType = application/json

### ============================================
### 根路徑
### ============================================
GET {{baseUrl}}/api/hello
###
GET {{baseUrl}}/api/health
###
POST {{baseUrl}}/api/test/echo
Content-Type: {{contentType}}

{
  "email": "apple@example.com",
  "name": "蘋果",
  "phone": "0912345678"
}
### 測試帶 params 的 URI
GET {{baseUrl}}/api/test/users/112233
### 測試帶多個 params 的 URI
GET {{baseUrl}}/api/test/users/112233/orders/order112233
### 測試帶多個 params 的 URI
GET {{baseUrl}}/api/test/error/500

### ============================================
### 寄信
### ============================================
POST {{baseUrl}}/send-email
Content-Type: {{contentType}}

{
  "to": "apple@example.com",
  "subject": "😍TEST Email",
  "html": "<b>Hello world</b>"
}
